spring.application.name=saberpro
server.port=8094

spring.datasource.url=jdbc:postgresql://ep-muddy-pine-ae8volp6-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_y7RViTdQF9Df
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true

# JSP correcto (ya NO el classpath)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
